name = "exe"
description = "Portable Executable format reader"
version = "0.1.0-dev"

authors = ["Miko Elbrecht"]
maintainers = ["Miko Elbrecht <tcgytsc@gmail.com>"]
maintainers-logins = ["ATPStorages"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://javart.zip/p/exe"
tags = ["exe"]

[[depends-on]]
byteflip = "~0.1.0-dev"

[[pins]]
byteflip = { path='../byteflip' }
