name = "exe"
description = "Portable Executable format reader"
version = "0.1.0-dev"

authors = ["Miko Elbrecht"]
maintainers = ["Miko Elbrecht <tcgytsc@gmail.com>"]
maintainers-logins = ["ATPStorages"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://javart.zip/p/exe"
tags = ["exe"]

[[depends-on]]
byteflippers = "~0.1.0-dev"

[[pins]]
byteflippers = { url='https://github.com/Bread-Experts-Group/byteflippers.git' }
